// Boost Software License - Version 1.0 - August 17th, 2003

// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:

// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

//ORIGINAL HEADER
/*
Copyright 2014-2015 Glen Joseph Fernandes
(glenjofe@gmail.com)

Distributed under the Boost Software License, Version 1.0.
(http://www.boost.org/LICENSE_1_0.txt)
*/

//MODIFIED FOR NAN


#ifndef NAN_ALIGNED_ALLOC_HPP
#define NAN_ALIGNED_ALLOC_HPP


#if defined(ALIGNED_ALLOC_USE_ALLOCATE)
#include "nan_aligned_alloc_generic_cpp17.hpp"
#elif defined(_MSC_VER) && !defined(UNDER_CE)
#include "nan_aligned_alloc_msvc_cpp17.hpp"
#elif defined(__MINGW32__) && (__MSVCRT_VERSION__ >= 0x0700)
#include "nan_aligned_alloc_msvc_cpp17.hpp"
#elif MAC_OS_X_VERSION_MIN_REQUIRED >= 1090
#include "nan_aligned_alloc_posix_cpp17.hpp"
#elif MAC_OS_X_VERSION_MIN_REQUIRED >= 1060
#include "nan_aligned_alloc_macos_cpp17.hpp"
#elif defined(__SunOS_5_11) || defined(__SunOS_5_12)
#include "nan_aligned_alloc_posix_cpp17.hpp"
#elif (_POSIX_C_SOURCE >= 200112L) || (_XOPEN_SOURCE >= 600)
#include "nan_aligned_alloc_posix_cpp17.hpp"
#elif defined(__linux__) /* this *should* work */
#include "nan_aligned_alloc_posix_cpp17.hpp"
#else
#pragma message "Falling back to generic aligned_alloc using allocator hack"
#include "nan_aligned_alloc_generic_cpp17.hpp"
#endif

#endif