# Tests are also run at: https://ci.appveyor.com/project/RodVagg/nan
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: ci
on:
  push:
  #  branches: [main]
  pull_request:
    branches: [main]
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x, 22.x, 23.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # - run: npm ci
      - run: npm install
      # - run: npm run build --if-present
      - run: npm run rebuild-tests-2017
      # - run: npm test
      - run: node node_modules/tap/bin/tap.js --gc test/js/*-test.js
